#                                           numpy 练习题

### numpy 的array操作

#### 1.导入numpy库

In [2]:
import numpy as np

#### 2.建立一个一维数组 a 初始化为[4,5,6], (1)输出a 的类型（type）(2)输出a的各维度的大小（shape）(3)输出 a的第一个元素（值为4）

In [12]:
a = np.array([4,5,6])
print(type(a))
print('a-dim:',a.shape)
print('a[0]:',a[0])

<class 'numpy.ndarray'>
a-dim: (3,)
a[0]: 4


#### 3.建立一个二维数组 b,初始化为 [ [4, 5, 6],[1, 2, 3]] (1)输出各维度的大小（shape）(2)输出 b(0,0)，b(0,1),b(1,1) 这三个元素（对应值分别为4,5,2）

In [14]:
b = np.array([[4,5,6],[1,2,3]])
print('b:\n',b)
print('b.shape():',b.shape[0],b.shape[1])
print('3 elements:',b[0,0],b[0][1],b[1][1])

b:
 [[4 5 6]
 [1 2 3]]
b.shape(): 2 3
3 elements: 4 5 2


#### 4.  (1)建立一个全0矩阵 a, 大小为 3x3; 类型为整型（提示: dtype = int）(2)建立一个全1矩阵b,大小为4x5;  (3)建立一个单位矩阵c ,大小为4x4; (4)生成一个随机数矩阵d,大小为 3x2.

In [15]:
a = np.zeros((3,3), dtype=int)
b = np.ones((4,5))
c = np.eye(4)
d = np.random.rand(3,2)
print('a=\n',a,'\nb=\n', b,'\nc=\n', c,'\nd=\n', d)

a=
 [[0 0 0]
 [0 0 0]
 [0 0 0]] 
b=
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
c=
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 
d=
 [[0.52670737 0.85922861]
 [0.098083   0.46532349]
 [0.49952082 0.52102511]]


#### 5. 建立一个数组 a,(值为[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]] ) ,(1)打印a; (2)输出  下标为(2,3),(0,0) 这两个数组元素的值

In [3]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f"a:{a}")
print(f"a[2][3]:{a[2][3]},a[0][0]:{a[0][0]}")

a:[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a[2][3]:12,a[0][0]:1


#### 6.把上一题的 a数组的 0到1行 2到3列，放到b里面去，（此处不需要从新建立a,直接调用即可）(1),输出b;(2) 输出b 的（0,0）这个元素的值

In [4]:
b=a[0:2,2:4]
print(b)
print(b[0][0])

[[3 4]
 [7 8]]
3


 #### 7. 把第5题中数组a的最后两行所有元素放到 c中，（提示： a[1:2, :]）(1)输出 c ; (2) 输出 c 中第一行的最后一个元素（提示，使用 -1                 表示最后一个元素）

In [5]:
c = a[1:3, :]
print(c)
print(c[0][-1])

[[ 5  6  7  8]
 [ 9 10 11 12]]
8


#### 8.建立数组a,初始化a为[[1, 2], [3, 4], [5, 6]]，输出 （0,0）（1,1）（2,0）这三个元素（提示： 使用 print(a[[0, 1, 2], [0, 1, 0]]) ）

In [7]:
a=np.array([[1,2],[3,4],[5,6]])
print("请告诉我(0,0) (1,1) (2,0)位置元素的值：")
print(a[[0,1,2],[0,1,0]])

请告诉我(0,0) (1,1) (2,0)位置元素的值：
[1 4 5]


#### 9.建立矩阵a ,初始化为[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]，输出(0,0),(1,2),(2,0),(3,1) (提示使用 b = np.array([0, 2, 0, 1])                     print(a[np.arange(4), b]))

In [15]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a[np.arange(4),[0,2,0,1]])

[ 1  6  7 11]


#### 10.对9 中输出的那四个元素，每个都加上10，然后重新输出矩阵a.(提示： a[np.arange(4), b] += 10 ）

In [ ]:
a[[[np.arange(4)]], [0,2,0,1]] += 10
print(a)
# 意外发现
# 1.横纵坐标不管套几层[]壳子，不影响匹配
# 2.如果先令a1=a，对a1做加操作，此后再输出a，值也变了，和a1相同
# 说明python的变量名就是一个标签，动替身也就是动本人

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### array 的数学运算

#### 11.  执行 x = np.array([1, 2])，然后输出 x 的数据类型

In [17]:
x = np.array([1,2])
print(f"x-type:{type(x)}")

x-type:<class 'numpy.ndarray'>


#### 12.执行 x = np.array([1.0, 2.0]) ，然后输出 x 的数据类类型

In [18]:
x = np.array([1.0,2.0])
print(f"x-type:{type(x)}")

x-type:<class 'numpy.ndarray'>


#### 13.执行 x = np.array([[1, 2], [3, 4]], dtype=np.float64) ，y = np.array([[5, 6], [7, 8]], dtype=np.float64)，然后输出 x+y ,和 np.add(x,y)

In [19]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
print(f"x + y:{x + y}")
print(f"np.add(x, y):{np.add(x, y)}")

x + y:[[ 6.  8.]
 [10. 12.]]
np.add(x, y):[[ 6.  8.]
 [10. 12.]]


#### 14. 利用 13题目中的x,y 输出 x-y 和 np.subtract(x,y)

In [20]:
print(f"x-y:{x-y}")
print(f"np.subtract(x,y):{np.subtract(x,y)}")

x-y:[[-4. -4.]
 [-4. -4.]]
np.subtract(x,y):[[-4. -4.]
 [-4. -4.]]


#### 15. 利用13题目中的x，y 输出 x*y ,和 np.multiply(x, y) 还有  np.dot(x,y),比较差异。然后自己换一个不是方阵的试试。

In [27]:
print('x:\n',x,'\n','y:\n',y)
print("x*y:\n",x*y)
print("np.multiply(x,y):\n",np.multiply(x,y))
print("np.dot(x,y):\n",np.dot(x,y))
print("本人的猜测，\n直接乘、multiply是按位乘，\ndot方法才是矩阵乘法.")
x1 = np.array([[1,1],[1,1]])
y1 = np.array([[8,4],[2,1]])
print("*,按位乘:\n",x1*y1)
print("np.multiply,按位乘:\n",np.multiply(x1,y1))
print("np.dot,矩阵乘:\n",np.dot(x1,y1))

x:
 [[1. 2.]
 [3. 4.]] 
 y:
 [[5. 6.]
 [7. 8.]]
x*y:
 [[ 5. 12.]
 [21. 32.]]
np.multiply(x,y):
 [[ 5. 12.]
 [21. 32.]]
np.dot(x,y):
 [[19. 22.]
 [43. 50.]]
本人的猜测，
直接乘、multiply是按位乘，
dot方法才是矩阵乘法.
*,按位乘:
 [[8 4]
 [2 1]]
np.multiply,按位乘:
 [[8 4]
 [2 1]]
np.dot,矩阵乘:
 [[10  5]
 [10  5]]


#### 16. 利用13题目中的x,y,输出 x / y .(提示 ： 使用函数 np.divide())

In [30]:
print("x:\n",x,"\ny:\n",y)
print("x/y:\n",np.divide(x,y))

x:
 [[1. 2.]
 [3. 4.]] 
y:
 [[5. 6.]
 [7. 8.]]
x/y:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


#### 17. 利用13题目中的x,输出 x的 开方。(提示： 使用函数 np.sqrt() )

In [31]:
print("x:\n",x,"\ny:\n",y)
print("x开方:\n",np.sqrt(x))

x:
 [[1. 2.]
 [3. 4.]] 
y:
 [[5. 6.]
 [7. 8.]]
x开方:
 [[1.         1.41421356]
 [1.73205081 2.        ]]


#### 18.利用13题目中的x,y ,执行 print(x.dot(y)) 和 print(np.dot(x,y))

In [35]:
print("x:\n",x,"\ny:\n",y)
print("x.dot(y):\n",x.dot(y)) #使用后x本身不变
print("np.dot(x,y):\n",np.dot(x,y))

x:
 [[1. 2.]
 [3. 4.]] 
y:
 [[5. 6.]
 [7. 8.]]
x.dot(y):
 [[19. 22.]
 [43. 50.]]
np.dot(x,y):
 [[19. 22.]
 [43. 50.]]


##### 19.利用13题目中的 x,进行求和。提示：输出三种求和 (1)print(np.sum(x)):   (2)print(np.sum(x，axis =0 ));   (3)print(np.sum(x,axis = 1))

In [37]:
print("x:\n",x)
print("np.sum:\n",np.sum(x))
print("np.sum(x,axis=0)\n",np.sum(x, axis=0))
print("np.sum(x,axis=1)\n",np.sum(x, axis=1))

x:
 [[1. 2.]
 [3. 4.]]
np.sum:
 10.0
np.sum(x,axis=0)
 [4. 6.]
np.sum(x,axis=1)
 [3. 7.]


#### 20.利用13题目中的 x,进行求平均数（提示：输出三种平均数(1)print(np.mean(x)) (2)print(np.mean(x,axis = 0))(3) print(np.mean(x,axis =1))）

In [38]:
print("x:\n",x)
print("np.mean:\n",np.mean(x))
print("np.mean(x,axis=0)\n",np.mean(x, axis=0))
print("np.mean(x,axis=1)\n",np.mean(x, axis=1))

x:
 [[1. 2.]
 [3. 4.]]
np.mean:
 2.5
np.mean(x,axis=0)
 [2. 3.]
np.mean(x,axis=1)
 [1.5 3.5]


#### 21.利用13题目中的x，对x 进行矩阵转置，然后输出转置后的结果，（提示： x.T 表示对 x 的转置）

In [39]:
print("x:\n",x)
print("x.T:\n",x.T)

x:
 [[1. 2.]
 [3. 4.]]
x.T:
 [[1. 3.]
 [2. 4.]]


#### 22.利用13题目中的x,求e的指数（提示： 函数 np.exp()）

In [40]:
print("x:\n",x)
print("np.exp(x):\n",np.exp(x))

x:
 [[1. 2.]
 [3. 4.]]
np.exp(x):
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


#### 23.利用13题目中的 x,求值最大的下标（提示(1)print(np.argmax(x)) ,(2) print(np.argmax(x, axis =0))(3)print(np.argmax(x),axis =1))

In [ ]:
print("x:\n",x)
x1 = np.concat((x, [[0,0],]))
print("x1:\n",x1)
print("np.argmax(x):\n",np.argmax(x))
print("np.argmax(x, axis=0):\n",np.argmax(x, axis=0))
print("np.argmax(x, axis=1):\n",np.argmax(x, axis=1))
print("这个测试用例写得不好，看不出区别.")
print("np.argmax(x):\n",np.argmax(x))
print("np.argmax(x, axis=0):\n",np.argmax(x, axis=0))
print("np.argmax(x, axis=1):\n",np.argmax(x, axis=1))

x:
 [[1. 2.]
 [3. 4.]]
x1:
 [[1. 2.]
 [3. 4.]
 [0. 0.]]
np.argmax(x):
 3
np.argmax(x, axis=0):
 [1 1]
np.argmax(x, axis=1):
 [1 1]


#### 24,画图，y=x*x 其中 x = np.arange(0, 100, 0.1) （提示这里用到  matplotlib.pyplot 库）

#### 25.画图。画正弦函数和余弦函数， x = np.arange(0, 3 * np.pi, 0.1)(提示：这里用到 np.sin() np.cos() 函数和 matplotlib.pyplot 库)